name: cwtch
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.19"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=count ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
      - name: Coverage report
        uses: seriousben/go-patch-cover-action@v1
