name: cwtch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=count ./...
      - name: Coverage report
        uses: seriousben/go-patch-cover-action@v1
